package bots.telegram.tarobot.util.enums;

import java.io.File;

public enum TarotCard {
    THE_FOOL("Шут", new File("src/main/media/TarotCard1.jpg")),
    THE_MAGICIAN("Маг", new File("src/main/media/TarotCard2.jpg")),
    THE_HIGH_PRIESTESS("Жрица", new File("src/main/media/TarotCard3.jpg")),
    THE_EMPRESS("Императрица", new File("src/main/media/TarotCard4.jpg")),
    THE_EMPEROR("Император", new File("src/main/media/TarotCard5.jpg")),
    THE_HIEROPHANT("Верховный жрец", new File("src/main/media/TarotCard6.jpg")),
    THE_LOVERS("Влюбленные", new File("src/main/media/TarotCard7.jpg")),
    THE_CHARIOT("Колесница", new File("src/main/media/TarotCard8.jpg")),
    STRENGTH("Сила", new File("src/main/media/TarotCard9.jpg")),
    THE_HERMIT("Отшельник", new File("src/main/media/TarotCard10.jpg")),
    WHEEL_OF_FORTUNE("Колесо фортуны", new File("src/main/media/TarotCard11.jpg")),
    JUSTICE("Правосудие", new File("src/main/media/TarotCard12.jpg")),
    THE_HANGED_MAN("Повешенный", new File("src/main/media/TarotCard13.jpg")),
    DEATH("Смерть", new File("src/main/media/TarotCard14.jpg")),
    TEMPERANCE("Умеренность", new File("src/main/media/TarotCard15.jpg")),
    THE_DEVIL("Дьявол", new File("src/main/media/TarotCard16.jpg")),
    THE_TOWER("Башня", new File("src/main/media/TarotCard17.jpg")),
    THE_STAR("Звезда", new File("src/main/media/TarotCard18.jpg")),
    THE_MOON("Луна", new File("src/main/media/TarotCard19.jpg")),
    THE_SUN("Солнце", new File("src/main/media/TarotCard20.jpg")),
    JUDGEMENT("Суд", new File("src/main/media/TarotCard21.jpg")),
    THE_WORLD("Мир", new File("src/main/media/TarotCard22.jpg")),
    ACE_OF_SWORDS("Туз мечей", new File("src/main/media/TarotCard23.jpg")),
    THE_TWO_OF_SWORDS("Двойка мечей", new File("src/main/media/TarotCard24.jpg")),
    THE_THREE_OF_SWORDS("Тройка мечей", new File("src/main/media/TarotCard25.jpg")),
    THE_FOUR_OF_SWORDS("Четверка мечей", new File("src/main/media/TarotCard26.jpg")),
    THE_FIVE_OF_SWORDS("Пятерка мечей", new File("src/main/media/TarotCard27.jpg")),
    THE_SIX_OF_SWORDS("Шестерка мечей", new File("src/main/media/TarotCard28.jpg")),
    THE_SEVEN_OF_SWORDS("Семерка мечей", new File("src/main/media/TarotCard29.jpg")),
    THE_EIGHT_OF_SWORDS("Восьмерка мечей", new File("src/main/media/TarotCard30.jpg")),
    THE_NINE_OF_SWORDS("Девятка мечей", new File("src/main/media/TarotCard31.jpg")),
    THE_TEN_OF_SWORDS("Десятка мечей", new File("src/main/media/TarotCard32.jpg")),
    PAGE_OF_SWORDS("Паж мечей", new File("src/main/media/TarotCard33.jpg")),
    KNIGHT_OF_SWORDS("Рыцарь мечей", new File("src/main/media/TarotCard34.jpg")),
    QUEEN_OF_SWORDS("Королева мечей", new File("src/main/media/TarotCard35.jpg")),
    KING_OF_SWORDS("Король мечей", new File("src/main/media/TarotCard36.jpg")),
    ACE_OF_WANDS("Туз жезлов", new File("src/main/media/TarotCard37.jpg")),
    THE_TWO_OF_WANDS("Двойка жезлов", new File("src/main/media/TarotCard38.jpg")),
    THE_THREE_OF_WANDS("Тройка жезлов", new File("src/main/media/TarotCard39.jpg")),
    THE_FOUR_OF_WANDS("Четверка жезлов", new File("src/main/media/TarotCard40.jpg")),
    THE_FIVE_OF_WANDS("Пятерка жезлов", new File("src/main/media/TarotCard41.jpg")),
    THE_SIX_OF_WANDS("Шестерка жезлов", new File("src/main/media/TarotCard42.jpg")),
    THE_SEVEN_OF_WANDS("Семерка жезлов", new File("src/main/media/TarotCard43.jpg")),
    THE_EIGHT_OF_WANDS("Восьмерка жезлов", new File("src/main/media/TarotCard44.jpg")),
    THE_NINE_OF_WANDS("Девятка жезлов", new File("src/main/media/TarotCard45.jpg")),
    THE_TEN_OF_WANDS("Десятка жезлов", new File("src/main/media/TarotCard46.jpg")),
    PAGE_OF_WANDS("Паж жезлов", new File("src/main/media/TarotCard47.jpg")),
    KNIGHT_OF_WANDS("Рыцарь жезлов", new File("src/main/media/TarotCard48.jpg")),
    QUEEN_OF_WANDS("Королева жезлов", new File("src/main/media/TarotCard49.jpg")),
    KING_OF_WANDS("Король жезлов", new File("src/main/media/TarotCard50.jpg")),
    ACE_OF_PENTACLES("Туз пентаклей", new File("src/main/media/TarotCard51.jpg")),
    THE_TWO_OF_PENTACLES("Двойка пентаклей", new File("src/main/media/TarotCard52.jpg")),
    THE_THREE_OF_PENTACLES("Тройка пентаклей", new File("src/main/media/TarotCard53.jpg")),
    THE_FOUR_OF_PENTACLES("Четверка пентаклей", new File("src/main/media/TarotCard54.jpg")),
    THE_FIVE_OF_PENTACLES("Пятерка пентаклей", new File("src/main/media/TarotCard55.jpg")),
    THE_SIX_OF_PENTACLES("Шестерка пентаклей", new File("src/main/media/TarotCard56.jpg")),
    THE_SEVEN_OF_PENTACLES("Семерка пентаклей", new File("src/main/media/TarotCard57.jpg")),
    THE_EIGHT_OF_PENTACLES("Восьмерка пентаклей", new File("src/main/media/TarotCard58.jpg")),
    THE_NINE_OF_PENTACLES("Девятка пентаклей", new File("src/main/media/TarotCard59.jpg")),
    THE_TEN_OF_PENTACLES("Десятка пентаклей", new File("src/main/media/TarotCard60.jpg")),
    PAGE_OF_PENTACLES("Паж пентаклей", new File("src/main/media/TarotCard61.jpg")),
    KNIGHT_OF_PENTACLES("Рыцарь пентаклей", new File("src/main/media/TarotCard62.jpg")),
    QUEEN_OF_PENTACLES("Королева пентаклей", new File("src/main/media/TarotCard63.jpg")),
    KING_OF_PENTACLES("Король пентаклей", new File("src/main/media/TarotCard64.jpg")),
    ACE_OF_CUPS("Туз кубков", new File("src/main/media/TarotCard65.jpg")),
    THE_TWO_OF_CUPS("Двойка кубков", new File("src/main/media/TarotCard66.jpg")),
    THE_THREE_OF_CUPS("Тройка кубков", new File("src/main/media/TarotCard67.jpg")),
    THE_FOUR_OF_CUPS("Четверка кубков", new File("src/main/media/TarotCard68.jpg")),
    THE_FIVE_OF_CUPS("Пятерка кубков", new File("src/main/media/TarotCard69.jpg")),
    THE_SIX_OF_CUPS("Шестерка кубков", new File("src/main/media/TarotCard70.jpg")),
    THE_SEVEN_OF_CUPS("Семерка кубков", new File("src/main/media/TarotCard71.jpg")),
    THE_EIGHT_OF_CUPS("Восьмерка кубков", new File("src/main/media/TarotCard72.jpg")),
    THE_NINE_OF_CUPS("Девятка кубков", new File("src/main/media/TarotCard73.jpg")),
    THE_TEN_OF_CUPS("Десятка кубков", new File("src/main/media/TarotCard74.jpg")),
    PAGE_OF_CUPS("Паж кубков", new File("src/main/media/TarotCard75.jpg")),
    KNIGHT_OF_CUPS("Рыцарь кубков", new File("src/main/media/TarotCard76.jpg")),
    QUEEN_OF_CUPS("Королева кубков", new File("src/main/media/TarotCard77.jpg")),
    KING_OF_CUPS("Король кубков", new File("src/main/media/TarotCard78.jpg"));

    TarotCard(String name, File image) {
    }
}
